name : CI

on:
  push:
    branches: master
  pull_request:
    branches: master

env:
  NB_KERNEL: python
  MPLBACKEND: Agg

jobs:

  build-docs:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Install seaborn
        run: |
          python -m pip install --upgrade pip
          pip install `cat ci/deps_latest.txt ci/utils.txt`
          pip install .

      - name: Install doc tools
        run: |
          pip install -r doc/requirements.txt
          sudo apt-get install pandoc

      - name: Build docs
        run: |
          make -C doc -j `nproc` notebooks
          make -C doc html


  run-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:

        python: [3.6.x, 3.7.x, 3.8.x, 3.9.x]
        target: [test]
        deps: [latest]
        backend: [agg]

        include:
          - python: 3.6.x
            target: unittests
            deps: pinned
            backend: agg
          - python: 3.9.x
            target: unittests
            deps: minimal
            backend: agg
          - python: 3.9.x
            target: test
            deps: latest
            backend: tkagg

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install seaborn
        run: |
          python -m pip install --upgrade pip
          pip install `cat ci/deps_${{ matrix.deps }}.txt ci/utils.txt`
          pip install .

      - name: Cache datastes
        run: python ci/cache_test_datasets.py

      - name: Run tests
        env:
          MPLBACKEND: ${{ matrix.backend }}
        run: |
          if [[ ${{ matrix.backend }} == 'tkagg' ]]; then PREFIX='xvfb-run -a'; fi
          $PREFIX make ${{ matrix.target }}

      - name: Upload coverage
        uses: codecov/codecov-action@v1
        if: ${{ success() }}
