name : CI

on:
  push:
    branches: master
  pull_request:
    branches: master

env:
  NB_KERNEL: python
  MPLBACKEND: Agg

jobs:

  build-docs:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          # Avoid Python 3.9 until scipy stack can cleanly build
          python-version: '3.8.x'

      - name: Install seaborn
        run: |
          python -m pip install --upgrade pip
          pip install `cat ci/deps_latest.txt ci/utils.txt`
          pip install .

      - name: Install doc tools
        run: |
          pip install -r doc/requirements.txt
          sudo apt-get install pandoc

      - name: Build docs
        run: make -C doc notebooks html
